apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: provider-aws
spec:
  credentials:
    source: Secret
    secretRef:
      name: localstack-aws-secret
      namespace: crossplane-system
      key: creds
  endpoint:
    hostnameImmutable: true
    services: [iam, s3, sqs, sts]
    url:
      type: Static
      static: http://172.28.58.86:4566
  skip_credentials_validation: true
  skip_metadata_api_check: true
  skip_requesting_account_id: true
  s3_use_path_style: true
